geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
]

geekshop/geekshop/urls.py
from django.conf.urls import include
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path

import mainapp.views as mainapp

urlpatterns = [
    path('', mainapp.main, name="main"),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('contact/', mainapp.contact, name='contact'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='index'),
    path('<int:pk>/', mainapp.products, name='category'),
    ]

geekshop/authapp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class ShopUser(AbstractUser):
    avatar = models.ImageField(upload_to='user_avatars', blank=True)
    age = models.PositiveIntegerField(verbose_name='Возраст')

geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='название категории', max_length=64, unique=True)
    description = models.TextField(verbose_name='Описание категории', blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products_images', blank=True)

    def __str__(self):
        return "{} ({})".format(self.name, self.category.name)


def create_superuser(self, username, email, password, **extra_fields):
    extra_fields.setdefault('is_staff', True)
    extra_fields.setdefault('is_superuser', True)

    if extra_fields.get('is_staff') is not True:
        raise ValueError('Superuser must have is_staff=True.')
    if extra_fields.get('is_superuser') is not True:
        raise ValueError('Superuser must have is_superuser=True.')

    return self._create_user(username, email, password, **extra_fields)

geekshop/authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm

from .models import ShopUser

class ShopUserLoginForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(ShopUserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

geekshop/authapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from authapp.forms import ShopUserLoginForm
from django.contrib import auth
from django.urls import reverse

# Create your views here.
def login(request):
    title = 'вход'

    login_form = ShopUserLoginForm(data=request.POST)
    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect(reverse('main'))

    content = {
        'title': title,
        'login_form': login_form
    }
    return render(request, 'authapp/login.html', content)

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main'))

geekshop/mainapp/views.py
from django.shortcuts import render

from mainapp.models import ProductCategory, Product


def main(request):
    title = "главная"
    products = [
        {
            'name': 'Отличный стул',
            'disc': 'Расположитесь с комфортов',
            'image_scr': 'product-1.jpg',
            'image_href': '/product/1/',
            'alt': 'продукт 1'
        },
        {
            'name': 'Стул повышенного качества',
            'disc': 'Не оторваться',
            'image_scr': 'product-2.jpg',
            'image_href': '/product/2/',
            'alt': 'продукт 2'
        }
    ]
    content = {
        "title": title,
        "products": products
    }

    return render(request, 'mainapp/index.html', content)
    

def products(request, pk=None):
    print(pk)

    title = "продукты"
    links_menu = ProductCategory.objects.all()
    same_products = Product.objects.all()

    content = {
        'title': title,
        'links_menu': links_menu,
        'same_products': same_products
    }
    return render(request, 'mainapp/products.html', content)


def contact(request):
    return render(request, 'mainapp/contact.html')

geekshop/authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet"	type="text/css" href= "{% static 'css/bootstrap.min.css' %}" >
        <link rel="stylesheet"	type="text/css" href= "{% static 'css/style.css' %}" >
        <link rel="stylesheet"	href= "{% static 'fonts/font-awesome/css/font-awesome.css' %}" >
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
<div class="container">
    <div class="login">
        <div class="h2 text-center head">
            Вход в систему
        </div>
        {% block content %}
        {% endblock %}
    </div>
</div>
</body>
</html>

geekshop/authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}

{% block content %}
    <form class="form-horizontal" action="{% url 'auth:login' %}" method="post">
        {% csrf_token %}
        {{ login_form.as_p}}
        <br>
        <input class="form-control" type="submit" value="войти">
    </form>
{% endblock %}

geekshop/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<meta charset= "utf-8">
	<title>
		{% block title %}
			{{ title|capfirst }}
		{% endblock %}
	</title>
	{% block css %}
		<link rel="stylesheet"	type="text/css" href= "{% static 'css/style.css' %}" >
		<link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}" >
	{% endblock %}
	{% block js %}

	{% endblock %}
</head>
<body>
<div class ="container">
	{% block menu %}

	{% endblock %}
	<div class ="content">
		{% block content %}

		{% endblock %}
	</div >
</div>
{% block footer %}
	<div class="footer">
		<div class="text - footer">
			<h3>контакты</h3>
		</div>
		<div class="text-footer">
			<h3>полезная информация</h3>
		</div>
	</div>
{% endblock %}
	
</body>
</html>

geekshop/mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block menu%}
	<div class="hero">
		<div class="header clearfix">
			<a href="/" class="logo"></a>
			{% include "mainapp/includes/inc_menu.html"%}
			<a href="#" class="search"></a>
            <a href="#" class="basket"></a>
		</div>
		<h1>наши контакты</h1>
	</div>
{% endblock %}

{% block content %}
    <div class="location">
        <div class="location-1">
            <i class="fa fa-map-marker fa-5x"></i>
            <h4>Москва</h4>
            <div class="contacts">
                <h5>Телефон</h5>
                <p>+7-888-888-8888</p>
            </div>
            <div class="contacts">
                <h5>Email</h5>
                <p>info@geekshop.ru</p>
            </div>
            <div class="contacts">
                <h5>Адрес</h5>
                <p>В пределах МКАД</p>
            </div>
        </div>
        <div class="location-1">
            <i class="fa fa-map-marker fa-5x"></i>
            <h4>Москва</h4>
            <div class="contacts">
                <h5>Телефон</h5>
                <p>+7-888-888-8888</p>
            </div>
            <div class="contacts">
                <h5>Email</h5>
                <p>info@geekshop.ru</p>
            </div>
            <div class="contacts">
                <h5>Адрес</h5>
                <p>В пределах МКАД</p>
            </div>
        </div>
        <div class="location-1">
            <i class="fa fa-map-marker fa-5x"></i>
            <h4>Москва</h4>
            <div class="contacts">
                <h5>Телефон</h5>
                <p>+7-888-888-8888</p>
            </div>
            <div class="contacts">
                <h5>Email</h5>
                <p>info@geekshop.ru</p>
            </div>
            <div class="contacts">
                <h5>Адрес</h5>
                <p>В пределах МКАД</p>
            </div>
        </div>
    </div>

    <div class="clr"></div>
{% endblock %}

{% block footer %}
<div class="footer">
    <div class="clearfix">
        <div class="text-footer">
            <h3>контакты</h3>
        </div>
        <div class="text-footer">
            <h3>полезная информация</h3>
        </div>
        <div class="text-footer clearfix">
            <h3>Оставайтесь на связи</h3>
            <p>Подписаться на новости и рассылки</p>
            <form>
                <input type="email" name="email" placeholder="ваш email">
                <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
            </form>
        </div>
    </div>
    <p class="small">&copy; GB 2017</p>
    <div class="social">
        <a href="#" class="social1"></a>
        <a href="#" class="social2"></a>
        <a href="#" class="social3"></a>
        <a href="#" class="social4"></a>
    </div>
    <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
</div>
{% endblock %}

geekshop/mainapp/templates/mainapp/includes/inc_categories_menu.html
<ul class="links-menu">
    <li>
        <a href="{% url 'products:category' 0 %}">
            все
        </a>
    </li>
    {% for link in links_menu %}
        <li>
            <a href="{% url 'products:category' link.pk %}">
                {{ link.name }}
            </a>
        </li>
    {%endfor%}
</ul>

geekshop/mainapp/templates/mainapp/includes/inc_menu.html
<ul class="menu">
    <li>
        <a href="{% url 'main' %}">
                домой
        </a>
    </li>
    <li>
        <a href="{% url 'products:index' %}">
            продукты
        </a>
    </li>
    <li>
        <a href="{% url 'contact' %}">
                контакты
        </a>
    </li>
</ul>

geekshop/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block menu%}
    <div class="slider">
        <div class="header clearfix">
            <a href="{% url 'main' %}" class="logo"></a>
            {% include "mainapp/includes/inc_menu.html" %}
            <a href="#" class="search"></a>
            <a href="#" class="basket"></a>
        </div>
        <div class="text-slider">
            <h3 class="green">тенденции</h3>
            <h3 class="big"> удобные стулья</h3>
            <p>Новый уровень комфорта. Отличные характеристики.</p>
            <a href="#" class="button-order">заказать <img src="{% static 'img/arrow.png' %}" alt=""></a>
        </div>
        <div class="navi">
            <a href="#"></a><a href="#"></a><a href="#"></a>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="featured">
        <div class="featured-menu">
                <a class="active" href="#">Популярные</a><a href="#">Новинки</a>
        </div>
        <a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
        <div class="clearfix">
        </div>
        <div class="tab-content">
            {% for product in products %}
                <div class="block">
                    <a href="{{ product.image_href }}"><img src="{% static 'img/' %}{{product.image_scr}}"
                                                            alt="{{product.alt}}">
                        <div class="text">
                            <img src="{% static 'img/icon-hover.png' %}" alt="/static/img">
                            <h4>{{ product.name }}</h4>
                            <p>{{ product.disc }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="clr"></div>
{% endblock %}


{% block footer %}
<div class="footer">
    <div class="clearfix">
        <div class="text-footer">
            <h3>контакты</h3>
        </div>
        <div class="text-footer">
            <h3>полезная информация</h3>
        </div>
        <div class="text-footer clearfix">
            <h3>Оставайтесь на связи</h3>
            <p>Подписаться на новости и рассылки</p>
            <form>
                <input type="email" name="email" placeholder="ваш email">
                <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
            </form>
        </div>
    </div>
    <p class="small">&copy; GB 2017</p>
    <div class="social">
        <a href="#" class="social1"></a>
        <a href="#" class="social2"></a>
        <a href="#" class="social3"></a>
        <a href="#" class="social4"></a>
    </div>
    <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
</div>
{% endblock %}

geekshop/mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}


{% block menu %}
    <div class="hero-white">
        <div class="header clearfix">
            <a href="/" class="logo"></a>
            {% include "mainapp/includes/inc_menu.html"%}
            <a href="#" class="search"></a>
            <a href="#" class="basket"></a>
        </div>
    </div>
{% endblock %}
{% block content %}
    <div class="details">
        <div class="links clearfix">
            {% include "mainapp/includes/inc_categories_menu.html"%}
        </div>

        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="{% static 'img/slider1.jpg' %}">
                </div>
                <div class="slider-control">
                    <div class="block">
                        <a href="#"><img src="{% static 'img/controll.jpg' %}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="{% static 'img/controll1.jpg' %}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="{% static 'img/controll2.jpg' %}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">Отличный стул</h3>
                <h3 class="red">горячее предложение</h3>
                <p class="price"> 2585.9 <span>руб</span></p>
                <a href="#" class="red-button">
                    заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    <p>Расположитесь комфортно.</p>
                    <p>Отличное качество материалов
                    позволит вам это.</p>
                    <p>Различные цвета</p>
                    <p>высочайший уровень
                    эргономики и прочность.</p>
                </div>
            </div>
        </div>

        <div class="related">
            <div class="title clearfix">
                <h2>Похожие продукты</h2>
                <a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
            </div>
            <div class="related-products clearfix">
                {% for product in same_products %}
                    <div class="block">
                        <a href="#"><img src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
                            <div class="text">
                                <img src="{% static 'img/icon-hover.png' %}" alt="img">
                                <h3>Категория: {{ product.category.name }}</h3>
                                <h4>Название: {{ product.name }}</h4>
                                <p>Описание: {{ product.description }}</p>
                                <p>Цена: {{ product.price}}</p>
                                <p>На складе: {{ product.quantity }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="clr"></div>

{% endblock %}

{% block footer %}
<div class="footer">
    <div class="clearfix">
        <div class="text-footer">
            <h3>контакты</h3>
        </div>
        <div class="text-footer">
            <h3>полезная информация</h3>
        </div>
        <div class="text-footer clearfix">
            <h3>Оставайтесь на связи</h3>
            <p>Подписаться на новости и рассылки</p>
            <form>
                <input type="email" name="email" placeholder="ваш email">
                <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
            </form>
        </div>
    </div>
    <p class="small">&copy; GB 2017</p>
    <div class="social">
        <a href="#" class="social1"></a>
        <a href="#" class="social2"></a>
        <a href="#" class="social3"></a>
        <a href="#" class="social4"></a>
    </div>
    <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
</div>
{% endblock %}